### ISSUE TITLE
Source generators don't need target framework .NET 5

### ISSUE THREAD

**Issue by kzrnm** [archi-Doc/ValueLink#37]
> CrossLink uses Source Generator, so the Target Framework should be .NET 5 or later.

Source generators don't need target framework **.NET 5**.
Source generators need **.NET 5 generation compiler.** 
You can use source generators in project that target .NET Core 3 or earlier, .NET Standard, or .NET Framework. 

## 日本語

> ソースジェネレーターなので、ターゲットフレームワークは .NET 5 以降です。

ソースジェネレーターは **.NET 5** をターゲットフレームワークにする必要はありません。
必要なのは **.NET 5世代のコンパイラ** です。
ターゲットフレームワークが .NET Core 3 以前でも .NET Standard でも .NET Framework でも使えます。

**Comment by archi-Doc** [comment]
That's my big mistake.
Thank you for pointing it out. I'll fix it later.

**Comment by archi-Doc** [comment]
#38
